# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

budget:
  minAvailable : 1

scheduler: 1
worker: 1

workspace:
  image:
    repository: anishdhanka/workspace
    tag: latest
    pullPolicy: Always


nginx:
  image:
    repository: anishdhanka/nginx
    tag: latest
    pullPolicy: Always


phpfpm:
  image:
    repository: anishdhanka/php-fpm
    tag: latest
    pullPolicy: Always

phpworker:
  image:
    repository: anishdhanka/php-worker
    tag: latest
    pullPolicy: Always


# use if image registry if private
#imagePullSecrets: [{'name': 'docker-secret'}]


phpworkernameOverride: 'phpworker'
nginxnameOverride: 'nginx'
phpfpmnameOverride: 'phpfpm'
workspacenameOverride: 'workspace'


config:
  APP_NAME : 'Laravel'
  APP_ENV : 'local'
  APP_DEBUG: 'true'
  APP_URL: 'http://localhost'

  LOG_CHANNEL: 'stack'

  DB_CONNECTION: 'mysql'

  DB_PORT: '3306'


  BROADCAST_DRIVER: 'redis'
  CACHE_DRIVER: 'redis'
  QUEUE_CONNECTION: 'redis'
  SESSION_DRIVER: 'redis'
  SESSION_LIFETIME: '120'


  REDIS_PORT: '6379'

  MAIL_MAILER: 'smtp'
  MAIL_HOST: 'smtp.mailtrap.io'
  MAIL_PORT: '2525'

  MAIL_ENCRYPTION: 'null'
  MAIL_FROM_ADDRESS: 'null'
  MAIL_FROM_NAME: ''

  PUSHER_APP_CLUSTER: 'mt1'




APP_KEY: 'base64:N0i/V07eZ29AYP2wXS3DXLykiOLY2Z2Eo2KPaesV9Zs='
DB_HOST: '127.0.0.1'
DB_DATABASE: 'laravel'
DB_USERNAME: 'root'
DB_PASSWORD: ''
REDIS_HOST: '127.0.0.1'
REDIS_PASSWORD: 'null'
PUSHER_APP_ID: ''
PUSHER_APP_KEY: ''
PUSHER_APP_SECRET: ''
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''
AWS_DEFAULT_REGION: ''
AWS_BUCKET: ''
MAIL_USERNAME: 'null'
MAIL_PASSWORD: 'null'
MIX_PUSHER_APP_KEY: ''
MIX_PUSHER_APP_CLUSTER: ''
#####


service:
  type: ClusterIP
  port: 80
  targetPort: 80


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}





